import '../styles/globals.css'; // 必要なグローバルCSSのインポート

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  keywords: 'Next.js, React, Calendar',
  author: 'Your Name'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta name="author" content={metadata.author} />
      </head>
      <body>{children}</body>
    </html>
  );
}